services:
  # Fetcher - получает данные с API и публикует в NATS
  fetcher:
    build: ./fetcher
    container_name: city-weather-fetcher
    depends_on:
      - redis
      - nats
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      NATS_URL: nats://nats-server:4222
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./fetcher:/app
    working_dir: /app
    command: bundle exec sidekiq -r ./config/initializers/sidekiq_cron.rb -C config/sidekiq.yml

  # Viewer - отображение данных
  viewer:
    build: ./viewer
    container_name: city-weather-viewer
    depends_on:
      - nats
      - postgres
    environment:
      NATS_URL: nats://nats-server:4222
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/viewer_development
    ports:
      - "3000:3000"
    volumes:
      - ./viewer:/app
    working_dir: /app
    command: bash -c "bin/rails s -b 0.0.0.0 -p 3000"

  # Viewer Sidekiq - синхронизация данных из NATS в Postgres
  viewer-sidekiq:
    build: ./viewer
    container_name: city-weather-viewer-sidekiq
    depends_on:
      - redis
      - nats
      - postgres
    environment:
      NATS_URL: nats://nats-server:4222
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/viewer_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./viewer:/app
    working_dir: /app
    command: bundle exec sidekiq -r ./config/initializers/sidekiq_cron.rb -C config/sidekiq.yml

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  nats:
    image: nats:2.11.8
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-DV"]

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: viewer_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
