services:
  fetcher:
    build: ./fetcher
    container_name: city-weather-fetcher
    depends_on:
      - nats
      - redis
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      NATS_URL: nats://nats-server:4222
      REDIS_URL: redis://redis:6379/0
    command: ruby bin/fetch_weather.rb

  sidekiq:
    build: ./fetcher
    container_name: city-weather-sidekiq
    depends_on:
      - redis
      - nats
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      NATS_URL: nats://nats-server:4222
      REDIS_URL: redis://redis:6379/0
    command: bundle exec sidekiq -r ./config/initializers/sidekiq_cron.rb -C config/sidekiq.yml

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  nats:
    image: nats:2.11.8
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-DV"]
