default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_NAME") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_NAME") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_NAME") %>
