concurrency: 5
queues:
  - default

require: ./config/environment.rb

schedule:
  weather_sync:
    cron: "*/10 * * * *"
    class: "WeatherSyncWorker"
    queue: default
    description: "Sync weather data from NATS to Postgres every 10 minutes"
